# 项目配置
forum:
  # 项目名称
  name: school-forum
  # 项目标题
  title: 校园论坛系统
  # 项目描述
  description: 论坛系统接口文档
  # 项目版本
  version: 1.0.0

# 验证码配置
customer-captcha:
  # 支持的类型 spec，math，chinese
  type: spec
  # 验证码的宽
  width: 100
  # 验证码的高度
  height: 40
  # 验证码的长度
  len: 4
  # 验证码的字体类型 0 到 9
  font: 9
  # 保存时间 秒位单位
  time: 60

# 服务配置
server:
  port: 9527

# spring 配置
spring:
  profiles:
    active: dev
  application:
    name: forum
  # 日期格式化配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  data:
    # redis 配置
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: ''
      # 连接超时
      connect-timeout: 10s
      # 读取超时
      timeout: 6s
      lettuce:
        pool:
          max-active: 200
          max-idle: 10
          min-idle: 1
          max-wait: -1ms

# MP 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    use-generated-keys: true
    cache-enabled: true
  global-config:
    db-config:
      id-type: auto
    banner: false
  # 搜索指定包别名
  type-aliases-package: com.sakura.**.entity
  # mapper 映射文件
  mapper-locations: classpath*:mapper/**/*Mapper.xml
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

logging:
  level:
    com.sakura: debug
    org.springframework: info
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
  config: classpath:logback.xml

sa-token:
  is-log: true
  is-print: false