# 项目配置
fourm:
  # 项目名称
  name: school-forum
  # 项目标题
  title: 校园论坛系统
  # 项目描述
  description: 论坛系统接口文档
  # 项目版本
  version: 1.0.0
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math
  
# 服务配置
server:
  port: 9527

# spring 配置
spring:
  profiles:
    active: dev
  application:
    name: forum

# MP 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    use-generated-keys: true
    cache-enabled: true
  global-config:
    db-config:
      id-type: auto
    banner: false
  # 搜索指定包别名
  type-aliases-package: com.sakura.**.pojo
  # mapper 映射文件
  mapper-locations: classpath*:mapper/**/*Mapper.xml
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs